#!/usr/bin/env python3
"""Generate a THIRD_PARTY_NOTICES.md from a scan_licenses.py inventory JSON.

Redistributing the binary triggers notice-retention duties: Apache-2.0 (§4d),
the BSD/MIT/ISC copyright lines, and the MPL-2.0 source-availability notice.
This emits the standard form — a per-dependency listing followed by the full,
de-duplicated license texts — so those duties are met in one file.

  python3 gen_notices.py --json inventory.json --out THIRD_PARTY_NOTICES.md

Only modules that actually ship are included: the Go set already comes from
`go list -deps ./cmd/...`, and for npm only runtime (bundled) deps are listed.
"""

import argparse
import hashlib
import json
import os
import re


def read_text(d):
    if not d or not os.path.isdir(d):
        return None
    for e in sorted(os.listdir(d)):
        if re.match(r"^(licen[sc]e|copying|unlicense)", e, re.I) and "doc" not in e.lower():
            try:
                return open(os.path.join(d, e), encoding="utf-8", errors="replace").read().strip()
            except OSError:
                return None
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--json", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--product", default="Cornus")
    args = ap.parse_args()

    inv = json.load(open(args.json))
    texts = {}          # sha -> full license text
    order = []          # preserve first-seen order of texts

    def register(text):
        if not text:
            return None
        sha = hashlib.sha256(text.encode()).hexdigest()[:12]
        if sha not in texts:
            texts[sha] = text
            order.append(sha)
        return sha

    lines = [
        f"# Third-party notices for {args.product}",
        "",
        "This binary bundles the following third-party components. Each is listed",
        "with its version and license; the full license texts follow at the end.",
        "This file is generated by `.agents/skills/audit-licenses` — do not edit by hand.",
        "",
    ]

    # --- Go modules (all in the list already ship) ---
    go = sorted(inv.get("go", []), key=lambda r: r["module"])
    if go:
        lines += ["## Go modules", "",
                  "| Module | Version | License |", "|---|---|---|"]
        for r in go:
            register(read_text(r.get("dir")))
            lines.append(f"| `{r['module']}` | {r['version']} | {r['license']} |")
        lines.append("")

    # --- npm runtime (bundled) modules only ---
    runtime = set(inv.get("npm_runtime", []))
    npm = sorted([r for r in inv.get("npm", []) if r["module"] in runtime],
                 key=lambda r: r["module"])
    if npm:
        lines += ["## Web frontend (npm, bundled into the embedded SPA)", "",
                  "| Package | License |", "|---|---|"]
        for r in npm:
            register(read_text(r.get("dir")))
            lines.append(f"| `{r['module']}` | {r['license']} |")
        lines.append("")

    # --- Vendored copies ---
    vend = inv.get("vendored", [])
    if vend:
        lines += ["## Vendored components (under `third_party/`)", ""]
        for v in vend:
            note = ""
            if v["category"] == "weak-copyleft":
                note = (" — **modified copy**; source is provided in-tree under "
                        "the same license as required")
            lines.append(f"- `{v['path']}` (origin `{v['origin']}`, {v['license']}){note}")
        lines.append("")

    # --- Full de-duplicated license texts ---
    lines += ["## License texts", "",
              f"The {len(order)} distinct license texts referenced above follow.", ""]
    for i, sha in enumerate(order, 1):
        lines += [f"<details><summary>License text #{i} ({sha})</summary>", "",
                  "```", texts[sha], "```", "", "</details>", ""]

    with open(args.out, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"Wrote {args.out}: {len(go)} Go modules, {len(npm)} bundled npm packages, "
          f"{len(vend)} vendored, {len(order)} distinct license texts.")


if __name__ == "__main__":
    main()
