//go:build linux

package barehost

// Managed /etc/resolv.conf files for guest containers, bind-mounted like the
// managed /etc/hosts. Each instance's resolv.conf points at the cornus DNS
// resolver (its bridge gateway) first, with host upstreams as fallback, plus any
// compose `dns_search` domains. Written temp+rename at create time (nothing
// mounts it yet); unlike /etc/hosts it is never rewritten in place (the resolver
// set is fixed for an instance's lifetime), so a rename is safe here.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
)

// resolvStore owns the per-instance resolv.conf files under <DataDir>/bare/resolv/.
type resolvStore struct {
	mu  sync.Mutex
	dir string
}

func newResolvStore(dataDir string) *resolvStore {
	return &resolvStore{dir: filepath.Join(dataDir, "bare", "resolv")}
}

func (r *resolvStore) path(id string) string { return filepath.Join(r.dir, id) }

// create writes an instance's resolv.conf (nameservers in order, optional search
// domains and options) and returns its path for the /etc/resolv.conf bind mount.
func (r *resolvStore) create(id string, nameservers, search, options []string) (string, error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	if err := os.MkdirAll(r.dir, 0o755); err != nil {
		return "", fmt.Errorf("bare: create resolv dir: %w", err)
	}
	var sb strings.Builder
	sb.WriteString("# generated by cornus (bare backend); do not edit\n")
	for _, ns := range nameservers {
		fmt.Fprintf(&sb, "nameserver %s\n", ns)
	}
	if len(search) > 0 {
		fmt.Fprintf(&sb, "search %s\n", strings.Join(search, " "))
	}
	if len(options) > 0 {
		fmt.Fprintf(&sb, "options %s\n", strings.Join(options, " "))
	}
	path := r.path(id)
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(sb.String()), 0o644); err != nil {
		return "", fmt.Errorf("bare: write resolv.conf: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		return "", fmt.Errorf("bare: install resolv.conf: %w", err)
	}
	return path, nil
}

// remove deletes an instance's resolv.conf (best-effort).
func (r *resolvStore) remove(id string) {
	r.mu.Lock()
	defer r.mu.Unlock()
	_ = os.Remove(r.path(id))
}
