package setupwiz

import (
	"fmt"
	"net/url"
	"strings"
	"text/template"
)

// systemdData parameterizes the remote-host systemd unit.
type systemdData struct {
	RemoteAddr string
	Containerd bool
}

// helmData parameterizes the kube helm values snippet.
type helmData struct {
	Exposure      string // nodePort | clusterIP | ingress
	AdvertiseHost string
	Audience      string
}

var systemdTemplate = template.Must(template.New("unit").Parse(`[Unit]
Description=cornus server
After=network-online.target
Wants=network-online.target

[Service]
Environment=CORNUS_DATA=/var/lib/cornus
{{- if .Containerd}}
Environment=CORNUS_DEPLOY_BACKEND=containerd
{{- end}}
ExecStart=/usr/local/bin/cornus serve --addr {{.RemoteAddr}}
Restart=on-failure
{{- if .Containerd}}
# containerd backend needs root and CNI plugins in /opt/cni/bin
User=root
{{- end}}

[Install]
WantedBy=multi-user.target
`))

var helmTemplate = template.Must(template.New("values").Parse(`deployBackend: kubernetes
registry:
  exposure: {{.Exposure}}
{{- if .AdvertiseHost}}
  advertiseHost: {{.AdvertiseHost}}
{{- end}}
{{- if .Audience}}
auth:
  jwt:
    audience: {{.Audience}}
{{- end}}
`))

func renderSystemd(d systemdData) (string, error) {
	if d.RemoteAddr == "" {
		d.RemoteAddr = "127.0.0.1:5000"
	}
	var b strings.Builder
	if err := systemdTemplate.Execute(&b, d); err != nil {
		return "", err
	}
	return b.String(), nil
}

func renderHelm(d helmData) (string, error) {
	if d.Exposure == "" {
		d.Exposure = "nodePort"
	}
	var b strings.Builder
	if err := helmTemplate.Execute(&b, d); err != nil {
		return "", err
	}
	return b.String(), nil
}

var (
	sshArtifactNotes = []string{
		"copy it to the remote host: scp cornus.service HOST:/etc/systemd/system/",
		"enable it: ssh HOST 'sudo systemctl daemon-reload && sudo systemctl enable --now cornus'",
	}
	helmArtifactNotes = []string{
		"install with it: helm install cornus oci://ghcr.io/moriyoshi/charts/cornus -f cornus-values.yaml",
	}
	// Preflight first, deliberately: a wrong bind here does not fail at startup,
	// it fails silently at deploy time, so checking is cheapest before anything
	// is running.
	composeArtifactNotes = []string{
		"check the binds: docker compose -f cornus-compose.yaml run --rm cornus daemon preflight",
		"then start it: docker compose -f cornus-compose.yaml up -d",
	}
)

// writeArtifacts offers the scenario's setup artifact (a systemd unit for SSH
// hosts, a helm values snippet for kube), each ask-before-write.
func (w *Wizard) writeArtifacts(a *Answers) error {
	switch a.Scenario {
	case ScenarioSSHDocker, ScenarioSSHContainerd:
		containerd := a.Scenario == ScenarioSSHContainerd
		return w.offerArtifact("cornus.service", sshArtifactNotes, func() (string, error) {
			return renderSystemd(systemdData{RemoteAddr: a.SSHRemoteAddr, Containerd: containerd})
		})
	case ScenarioKubePortForward, ScenarioKubeURL:
		return w.offerArtifact("cornus-values.yaml", helmArtifactNotes, func() (string, error) {
			idx, err := w.ui.Select("Registry exposure for the helm values", "", []Option{
				{Label: "NodePort", Desc: "auto-advertises the node address (default)"},
				{Label: "ClusterIP", Desc: "in-cluster only; set advertiseHost"},
				{Label: "Ingress", Desc: "behind an ingress; set advertiseHost"},
			}, 0)
			if err != nil {
				return "", err
			}
			exposure := []string{"nodePort", "clusterIP", "ingress"}[idx]
			return renderHelm(helmData{Exposure: exposure, AdvertiseHost: a.RegistryHost, Audience: a.KubeAuthAudience})
		})
	case ScenarioDockerContainer:
		return w.offerArtifact("cornus-compose.yaml", composeArtifactNotes, func() (string, error) {
			return renderContainerCompose(containerComposeData{
				HostDataDir: a.ContainerDataDir,
				Port:        portOf(a.Server),
			})
		})
	}
	return nil
}

// containerComposeData is what the server-in-a-container artifact needs.
type containerComposeData struct {
	HostDataDir string
	Port        string
}

// containerComposeTemplate is the run recipe for a containerized server.
//
// Every line of it is load-bearing, and the comments say which failure each one
// prevents — because the failures are silent. A missing socket bind means no
// daemon at all; a missing data-dir bind means client-local mounts are refused;
// a data-dir bind without rshared means the server's own mount never reaches the
// daemon and the workload silently gets an empty directory.
var containerComposeTemplate = template.Must(template.New("compose").Parse(`# cornus server running as a container on the docker host it manages.
# Generated by ` + "`cornus setup`" + `. See https://cornus.dev/guides/server-in-a-container
services:
  cornus:
    image: ghcr.io/moriyoshi/cornus:latest
    command: ["serve", "--addr", ":{{.Port}}"]
    restart: unless-stopped
    # Needed to build images in-process and to perform the kernel 9P mount for
    # client-local mounts. Drop it if this server only deploys prebuilt images.
    privileged: true
    ports:
      - "127.0.0.1:{{.Port}}:{{.Port}}"
    environment:
      # The bind destination below and the server's data dir must be the same
      # path; state it rather than rely on the image's default.
      CORNUS_DATA: /var/lib/cornus
    volumes:
      # The host's docker daemon: without this there is no runtime to deploy to.
      - /var/run/docker.sock:/var/run/docker.sock
      # The data dir, as a HOST path so the daemon can resolve the mountpoints
      # the server hands it. rshared lets a mount the server makes inside the
      # container propagate out to the daemon; without it a client-local mount
      # silently becomes an empty directory in the workload.
      - {{.HostDataDir}}:/var/lib/cornus:rshared
`))

// renderContainerCompose renders the server-in-a-container run artifact.
func renderContainerCompose(d containerComposeData) (string, error) {
	if d.HostDataDir == "" {
		d.HostDataDir = "/srv/cornus"
	}
	if d.Port == "" {
		d.Port = "5000"
	}
	var b strings.Builder
	if err := containerComposeTemplate.Execute(&b, d); err != nil {
		return "", err
	}
	return b.String(), nil
}

// portOf extracts the port from a server URL, defaulting to 5000. The artifact
// publishes and binds that port, so it must match the profile the wizard just
// saved or the context points at nothing.
func portOf(server string) string {
	u, err := url.Parse(strings.TrimSpace(server))
	if err != nil {
		return "5000"
	}
	if p := u.Port(); p != "" {
		return p
	}
	return "5000"
}

// offerArtifact runs the {Write, Print, Skip} choice for one artifact. render is
// called lazily (only when not skipped) so a Skip never asks the artifact's
// follow-up questions. A Write onto an existing file confirms the overwrite and
// falls back to printing when declined.
func (w *Wizard) offerArtifact(name string, notes []string, render func() (string, error)) error {
	idx, err := w.ui.Select(fmt.Sprintf("Setup artifact: %s", name), "", []Option{
		{Label: "Write to a file", Desc: "create " + name + " in the current directory"},
		{Label: "Print to stdout", Desc: ""},
		{Label: "Skip", Desc: ""},
	}, 0)
	if err != nil {
		return err
	}
	if idx == 2 {
		return nil
	}
	content, err := render()
	if err != nil {
		return err
	}
	if idx == 1 {
		w.printArtifact(name, content, notes)
		return nil
	}
	// Write, guarding an existing file.
	if _, serr := w.Stat(name); serr == nil {
		ok, err := w.ui.Confirm(fmt.Sprintf("%s already exists. Overwrite it?", name), false)
		if err != nil {
			return err
		}
		if !ok {
			w.printArtifact(name, content, notes)
			return nil
		}
	}
	if err := w.WriteFile(name, []byte(content), 0o644); err != nil {
		return err
	}
	w.d.Done("wrote %s", name)
	for _, n := range notes {
		w.d.Info("%s", n)
	}
	return nil
}

// printArtifact writes the artifact to stdout (a result the user may pipe) and
// its follow-up notes to stderr.
func (w *Wizard) printArtifact(name, content string, notes []string) {
	w.d.Info("--- %s ---", name)
	fmt.Fprint(w.d.Out(), content)
	for _, n := range notes {
		w.d.Info("%s", n)
	}
}
